### ISSUE TITLE
Update Report and Project Name

### ISSUE THREAD

**Issue by jayasriram** [GHPReporter/Ghpr.Core#104]
Question on Changing Report Name:
I have successfully implemented GHP Reporter in my project but I seem the report name and project names do not update even after changing them on the json files.
I have updated the names on both the below files
Ghpr.Core.Settings.json
Ghpr.SpecFlow.Settings.json
Can you please let me know if I am doing it in the right way?
I see that there was an issue #76 closed after fix on version 0.9.3 but I am currently using 0.9.4 and I still have the issue.

**Comment by elv1s42** [comment]
Hi @jayasriram !

Can you please check the version of both packages you are using?
I've tested the case using our demo report: http://ghpreporter.github.io/report/index.html?currentTab=runs-stats

I've updated .json data: https://github.com/GHPReporter/GHPReporter.github.io/commit/945d31046fb31266326aed95c502f336a7ae1f55
And all changes are displayed on the site now.

Thank you.

**Comment by jayasriram** [comment]
@elv1s42 ,Thanks for the reply!
But I can see that both the nuget packages are pointing to 0.9.4 and I am making changes on both the json files
Ghpr.Core.Settings.json
Ghpr.SpecFlow.Settings.json
Should I change in both the files or is it one among the above?

**Comment by elv1s42** [comment]
Hi @jayasriram,
can o you please tell me what packages you are using? There are serveral Ghpr.SpecFlow packages (based on SpecFlow's unit test provider). I'll try to reproduce the issue.

Thank you

**Comment by jayasriram** [comment]
Hi @elv1s42 ,
Sure please find the screenshot attached.
![image](https://user-images.githubusercontent.com/46928916/53483783-2accd980-3a7a-11e9-9aea-eaaebe8d9f6f.png)

**Comment by elv1s42** [comment]
Hi @jayasriram ,
I've tried to reproduce the issue, but still no luck.
Can you please make sure that you have correct properties for your `Ghpr.SpecFlow.Settings.json` file?
You should use `Copy always` option for Ghpr Plugin to pick up correct .json file:
![image](https://user-images.githubusercontent.com/6689884/53487652-2c5bc900-3a9d-11e9-8e4f-b402113d0915.png)


Thank you

**Comment by jayasriram** [comment]
Awesome!! That worked now and thanks again for the help..

**Comment by elv1s42** [comment]
Great, I am closing the issue then, please feel free to raise a new one or reopen this if something goes wrong with these settings.
Thank you

**Comment by jayasriram** [comment]
I have got a quick doubt though. Which json takes priority. Is it Ghpr.Core.Settings or Ghpr.specflow.Settings?

**Comment by elv1s42** [comment]
`Ghpr.SpecFlow.Settings.json` should take priority, it is used by Ghpr.SpecFlow package

**Comment by jayasriram** [comment]
Thanks :)
