### ISSUE TITLE
[Feature] Ghpr configuration file for few projects

### ISSUE THREAD

**Issue by DmitriyGrabinskiy** [GHPReporter/Ghpr.Core#107]
Hello.

Here is my issue description:
Could you please help me with trouble with Ghpr.NUnit that I want to use in two projects.
I have added such NuGet package to my projects and also make all configurations according manual (https://github.com/GHPReporter/Ghpr.NUnit).
When I run tests from my 1st project - everythink is ok.
When run tests from 2nd project - all results are going to directory that was configured for 1st project (I want that each project have it own result directory).

I think this is because i have two different links to Ghpr.NUnit.dll in nunit.bundle.addins and nunit-console gets only first one.
So, my question, how to configure nUnit and Ghpr.NUnit to write Ghpr Reports to different directories.

---------------------------------------
I got such answer from you earlier:
By default Ghpr.Core takes the configuration from the file in the directory where the dll itself is located.

You can try to use two different commands to run your tests from to projects. Something like a .bat file or a powershell script to change the target location of the report (by changing .json config file).

Another option is that I can implement new config which will give you the ability to use destination folder per project.
Something like:
"outputPaths": [
    {"projectName": "MyProject1", "outputPath": "C:\\_GHPReporter_NUnit_Report\Project1"},
    {"projectName": "MyProject2", "outputPath": "C:\\_GHPReporter_NUnit_Report\Project2"}
  ]

It would be great to have one configuration file for few projects, so please pay attention to this and implement as much as possible.

**Comment by elv1s42** [comment]
This is now implemented and released in `v0.9.9`.

Please see related information in readme file here: https://github.com/GHPReporter/Ghpr.Core#about-settings-file
