### ISSUE TITLE
Compilation failure

### ISSUE THREAD

**Issue by davesliu** [GHPReporter/Ghpr.Core#114]
**Describe the bug**

I downloaded the latest version of Ghpr.Core. 
Open the Ghpr.Core.sln and click the "Build" button. It has one build error.

1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(5165,5): error MSB3073: The command "if Debug == Debug (xcopy "C:\git\Ghpr.Core\Ghpr.Controller.ts\bin\report\*.*" "C:\_GHPReporter_NUnit_Report" /r /y /e)" exited with code 2.

Could you help to give some comments for this issue?

BTW, I could click the Test Explorer of Ghpr.Core and the test cases can be executed successfully if I clicked Yes in the popped out warning dialog for build failure.

There is no test result content in the index.html of C:\_GHPReporter_Core_Report

(My Environment is VS2017)

**Comment by elv1s42** [comment]
Hi @davesliu !

If you want to build the project locally, you can simply remove the post-deployment event:
![image](https://user-images.githubusercontent.com/6689884/60093651-a6057a00-9752-11e9-8765-41014e9a0ea0.png)

The tests you see in the `Tests` folder are unit tests of the project itself, their run is not producing any reports.

If you want to use the report with any of frameworks like NUnit, MSTest or SpecFlow please see the usage details under corresponing repositories.
1. NUnit: https://github.com/GHPReporter/Ghpr.NUnit#usage
2. SpecFlow: https://github.com/GHPReporter/Ghpr.SpecFlow#usage
3. MSTest: https://github.com/GHPReporter/Ghpr.Console#usage

Also please note that SpecFlow 3 is not fully suupported an the moment.

Thank you

**Comment by davesliu** [comment]
@elv1s42  Thanks for your feedback :-)

I will try to use  https://github.com/GHPReporter/Ghpr.NUnit.Examples to see if the example works.

**Comment by elv1s42** [comment]
@davesliu sure. 
Please be aware that the examples repository may not be updated to the latest version, but you can update in in the NuGet Package Manager.
Thank you
