### ISSUE TITLE
Provide feature toggle for escaping test messages in report (#53)

### ISSUE THREAD

**Issue by GitSIPA** [GHPReporter/Ghpr.Core#128]
### **Problem**
With the release of #53 we noticed a problem in our test reports and the way we currently use GHPReporter with NUnit.

When we first started using GHPReporter we noticed that adding HTML elements and styling was possible for test messages. We thought it was a feature and took advantage of it.

We implemented a LogInterface on our side that nicely formats our test logs that are written during the test and adds HTML elements as well

### **Suggested/Requested Solution**
In order to continue using the latest version of GHPReporter in the future, we would need some kind of **feature toggle that we can set, so that escaping test messages is turned off** for us. 

If this is not possible, we would have to look for a different reporting solution for our tests, since the workaround to just keep an old verison of \src\js\ghpr.conroller is not a valid long term solution for us

### **Example of our Report Usage**
_due to corporate guidelines I had to anonymize parts of the screenshot_

![anonymized_report_screenshot](https://user-images.githubusercontent.com/1035887/65027895-6dcd9c00-d93b-11e9-8241-3f27d654fe5b.png)

**Comment by elv1s42** [comment]
Hi @GitSIPA !

Thank you for this issue. 
I think it's possible to add a new `escapeTestOutput` setting to turn off this feature for you. 

Also adding custom logging seems to me quite a good feature too. I was thinking about it but didn't have enough time to implement it properly. The idea was to add custom logger to support real-time test messages (for example in [markdown](https://en.wikipedia.org/wiki/Markdown))

**Comment by elv1s42** [comment]
Hi @GitSIPA !
I've started initial implementation for `escapeTestOutput` property. 

For the test output with some `html` tags we were not getting any output at all. For now the fix is done only on `.js` side of things, but the output will look more correct. Here is the example:
Output:
![image](https://user-images.githubusercontent.com/6689884/65434236-29546b80-de27-11e9-8076-d062c37c403f.png)

New result:
 ![image](https://user-images.githubusercontent.com/6689884/65433661-1c834800-de26-11e9-8d1e-ff9e9b488c60.png)

**Comment by elv1s42** [comment]
If you want to try this locally now, you can do the following things:
1. Add additional parameter to you settings file (`ReportSettings.json` file from `src` folder of your report):
![image](https://user-images.githubusercontent.com/6689884/65434404-6b7dad00-de27-11e9-9188-d6c688f1f9e9.png)
2. Replace the content of `ghpr.controller.js` file from `src/js` folder with version from [this branch](https://github.com/GHPReporter/Ghpr.Core/blob/a8f5b6b76fbb9d24ab1cde3d5d942a2e55880819/Ghpr.Controller.ts/report/src/js/ghpr.controller.js)
3. Refresh the report page with cache refresh (using Ctrl+F5 keys)

@GitSIPA, please let me know if you want to try this out locally

Thank you

**Comment by GitSIPA** [comment]
Hi @elv1s42 !

Thanks for implementing this enhancement. 
I'll try it locally this week and give you feedback on how it works on our side. 

thank you!

**Comment by elv1s42** [comment]
The changes are in `master` now, going to include them in the next release

**Comment by elv1s42** [comment]
This is now released as part of version `0.9.9.9`

**Comment by elv1s42** [comment]
Released. 
Please feel free to reopen this one a raise a new issue in case something is not working.
