### ISSUE TITLE
[Bug] NotExecuted test result is considered as Unknown

### ISSUE THREAD

**Issue by elv1s42** [GHPReporter/Ghpr.Core#138]
For MSTestV2 there is a test result status called "NotExecuted" which should be mapped to "Ignored" in the report:
![image](https://user-images.githubusercontent.com/6689884/68310373-f279a280-00c0-11ea-8fd8-5286d3dda9cf.png)

**Comment by elv1s42** [comment]
Fixed:
![image](https://user-images.githubusercontent.com/6689884/68314452-3e2f4a80-00c7-11ea-9615-61891bd267ab.png)

**Comment by yfrindel** [comment]
Could you tell me when this fix is scheduled to be integrated in the nugget package please ?

**Comment by elv1s42** [comment]
Hi @yfrindel !
Sorry for the delay. The Milestone is updated with target release date.

**Comment by yfrindel** [comment]
No problem, and thank you for this update.

**Comment by elv1s42** [comment]
Release in v0.9.10
