### ISSUE TITLE
Report in Jenkins is broken. 

### ISSUE THREAD

**Issue by georgigocev** [GHPReporter/Ghpr.Core#18]
Hi, we are using the reporting in our team. We run the tests on a nightly basis with Jenkins using Nunit runner.  The runs pass and i see the report generated on the Jenkins slave where i execute it. 
In order to display the report in Jenkins i am using HTML Plugin to which i point the report folder and the html file to be displayed. However the report looks empty in Jenkins: 
![image](https://cloud.githubusercontent.com/assets/25058184/21853197/c8efc408-d81e-11e6-98f3-6899c8bed253.png)
Can you advice if there is a solution of the problem.

**Comment by elv1s42** [comment]
Hi @georgigocev !

This problem may be related with Content Security Policy.

Please, take a look at this short instruction: https://github.com/GHPReporter/Ghpr.NUnit#how-to-publish-the-report-in-jenkins
I also moved this instruction to [Core README file](https://github.com/GHPReporter/Ghpr.Core#how-to-publish-the-report-in-jenkins)

You can also check if there are any errors inside browser console.

**Comment by elv1s42** [comment]
@georgigocev , please let me know if suggested instruction worked for you. 
If so, I am going to close this issue.

**Comment by georgigocev** [comment]
@elv1s42 We are working on the issue at the moment! I will let you know if we succeeded with your instructions in a day or two

**Comment by elv1s42** [comment]
Good, thanks for the update!

**Comment by georgigocev** [comment]
Hi what you provided as solution steps is enough. Thanks Evgeniy!

**Comment by elv1s42** [comment]
Good news, @georgigocev thanks for confirmation!
I will close this issue now.
