### ISSUE TITLE
Latest test run

### ISSUE THREAD

**Issue by xcyroo** [GHPReporter/Ghpr.Core#23]
Hi there,

is there any possibility to add a route so that I can display the latest test run? Something like ...runs/latest
Thanks!

Peter

**Comment by elv1s42** [comment]
Hello @xcyroo !

If I understand you corrctly, you want to able to use single URL for loading the latest run from all test runs?
Somthing like https://youreserver/report/runs/latest/index.html ?

At the moment you are able to open latest run with one click using 'Latest' button:
![image](https://cloud.githubusercontent.com/assets/6689884/22063948/6d80a2f8-dd92-11e6-8b8c-36aa636748cf.png)

**Comment by xcyroo** [comment]
Hi,

yes I would appreciate a single URL which navigates me to the latest run.
Is it acceptable for you?

Peter

**Comment by elv1s42** [comment]
@xcyroo I think it is possible to implement this feature like so: https://youreserver/report/runs/latest/index.html?loadLatest=true
and `loadLatest` parameter (when set to `true`) will force Ghpr to load the latest version.

Will this solution meet your requirements?

**Comment by xcyroo** [comment]
Hi, that solution will definitely meet my requirement.
Thanks!
Peter

**Comment by xcyroo** [comment]
Hi, loadLatest=true works well, you can close this one. Thanks!

**Comment by elv1s42** [comment]
Hi @xcyroo !
I thought this one is not included in the latest release, did you build the new version from the source code?

**Comment by xcyroo** [comment]
ahh, I just called /runs/index.html?loadLatest=true and it redirected me to the latest one so I thought this is in the latest release. I noticed that it redirects me to the latest run even if I call just /runs but that is probably just a luck. Isn't it?

**Comment by elv1s42** [comment]
@xcyroo , that's my bad! I fogot that by default if you open runs page it will load the latest one (if there are no parameters inside URL).
So yeah, there is no need to implement this feature at all!

**Comment by elv1s42** [comment]
Actually now there are to ways to open the latest test run page:
1. Use special parameter inside URL (this way will be added in the next release): http://ghpreporter.github.io/report/runs/index.html?loadLatest=true
2. Just use URL without any parameters: http://ghpreporter.github.io/report/runs/index.html

Both ways are working fine.

**Comment by elv1s42** [comment]
Closing this one as implemented. 
Works with Ghpr.Core 0.4.4+
