### ISSUE TITLE
Configurable count of test runs

### ISSUE THREAD

**Issue by xcyroo** [GHPReporter/Ghpr.Core#27]
Hi,
any possibility to add an option to configure how many test runs should be displayed?
Right now, when there is more than 30 test runs, the report is very disarranged.
I would like to set how many latest test runs should be displayed.
Thanks,
Peter

**Comment by elv1s42** [comment]
Hi!
Yeah, I agree, this one needs to be done.
I was thinking of two new settings, something like `testToDisplay` (for test history page) and `testRunsToDisplay` (for test runs page).

Do you think this way is acceptable for you?

**Comment by elv1s42** [comment]
Of course I mean displaying the latest (newest) tests and runs.

**Comment by xcyroo** [comment]
If those options holds a number that represents count of the latest items so I am ok with proposed settings.
+ if it will be empty or zero so it displays all items

Thanks,
Peter

**Comment by elv1s42** [comment]
Hi @xcyroo !
This feature is done, two new parameters were added:
You can find their description [here](https://github.com/GHPReporter/Ghpr.Core#about-settings-file).

New parameters are available in v 0.4.5 release.

**Comment by elv1s42** [comment]
@xcyroo please note, that if you will run tests and generate report into the folder where report already exists, you will need to **delete all three index.html files before test run** (they will appear again during test run).

**Comment by xcyroo** [comment]
thanks! I will update reporting addin today and let you know in case of an issue.

**Comment by elv1s42** [comment]
One issue small was found, #30 

Will fix it in the next few days

**Comment by elv1s42** [comment]
#30 is fixed now in v0.4.5.2
