### ISSUE TITLE
Ghpr to support new version of NUnit

### ISSUE THREAD

**Issue by nikembala** [GHPReporter/Ghpr.Core#32]
Hello,

When I run my project with the Ghpr integrated with the current .ddls I get the following error:
"Could not load file or assembly 'nunit.engine, Version=3.4.1.0, Culture=neutral, PublicKeyToken=2638cd05610744eb' or one of its dependencies. The system cannot find the file specified."
My nuget.engine is at 3.6.1

Should I roll back to previous versions?

Regards,
Niki

**Comment by elv1s42** [comment]
Hello @nikembala !

Are you sure that you are using the latest version of Ghpr.Core and Ghpr.NUnit?

Ghpr.NUnit depends on nunit.engine v3.6:
![2017-03-15 17_55_53-ghpr nunit_packages config at master ghpreporter_ghpr nunit](https://cloud.githubusercontent.com/assets/6689884/23954621/db0dc8a4-09a8-11e7-8f8c-6ca52b576e2c.png)

**Comment by nikembala** [comment]
Hello,

![image](https://cloud.githubusercontent.com/assets/18442755/23956920/9f8758ec-09a6-11e7-803e-ea3b0c7a0a8a.png)

I am on the latest version of Ghpr.Core/Ghpr.NUnit and I used the .dlls from https://github.com/GHPReporter/Ghpr.NUnit/releases

**Comment by elv1s42** [comment]
Ok, I see.

I think you need to take the latest .dll files from NuGet. If you are using NuGet package, you should be able to find this dlls inside packages folder within your project.

The dlls from https://github.com/GHPReporter/Ghpr.NUnit/releases are the old ones.

**Comment by nikembala** [comment]
Hello,

I copied .dlls from the packages folder - Ghpr.Core, Ghpr.NUnit and Newtonsoft.Json - now I have the error for newer version - "Could not load file or assembly 'nunit.engine, Version=**3.6.0.0**, Culture=neutral, PublicKeyToken=2638cd05610744eb' or one of its dependencies. The system cannot find the file specified."

Anyone else having this problem, idk if this is only on my machine or not.

**Comment by nikembala** [comment]
Hello,

As it is said "morning is wiser than evening".
In Ghpr.NUnit project in the packages - the version of NUnit.Engine is 3.6.0 - there is newer version released for that package - 3.6.1.
After I updated the packages of the Ghpr.NUnit project and copied the .dll from the locally updated project - the tests are running and the report is generated.

**Comment by nikembala** [comment]
@elv1s42, if you update that package and sync with the repo, this ticket should be closed.

**Comment by elv1s42** [comment]
@nikembala , thank you for help with this!

I will try to create NuGet package using interval notation for specifying version ranges, so in the future there won't be need to wait for new package of Ghpr.NUnit when new NUnit package will appear.

**Comment by nikembala** [comment]
I am not sure how would it work for furete releases, but it is woth the try.
Thank you!

**Comment by elv1s42** [comment]
@nikembala I've updated dependencies and created new NuGet packeges, v0.4.5.5

**Comment by nikembala** [comment]
Thank you!
Reviewed the changes - it is working with 3.6.1
