### ISSUE TITLE
Ghpr.Core error after package update

### ISSUE THREAD

**Issue by nikembala** [GHPReporter/Ghpr.Core#38]
Hello,

When I update Ghpr.Core from 0.4.6.0 to 0.4.6.5 and I try to find browse my "installed" packages from visual studio, I got the following error:
Item has already been added. Key in dictionary: 'lib/net452/Ghpr.Core.dll'  Key being added: 'lib/net452/Ghpr.Core.dll'
This does not happen with the 0.4.6.0 version.
Any idea why is that?

Regards.

**Comment by elv1s42** [comment]
Hello @nikembala,
this is related to #35 issue and already fixed with #37 

For now please use version 0.4.6.0.

This issue will be fixed in new version.
Sorry for the inconvenience.

**Comment by elv1s42** [comment]
I will close this issue when new version appear

**Comment by nikembala** [comment]
Thank you.

**Comment by elv1s42** [comment]
Fixed in new version. May require manual uninstall of previous version
