### ISSUE TITLE
Add Description Attribute in every test "Main information" area

### ISSUE THREAD

**Issue by jherbiere-giift** [GHPReporter/Ghpr.Core#42]
I am also trying to map the field you display with the list of attributes from [nunit](https://github.com/nunit/docs/wiki/Attributes). 
So far I don't know about Priority, Test type and Message.
![image](https://cloud.githubusercontent.com/assets/3124325/26150111/8587a248-3b2f-11e7-966f-53afcb039569.png).

**Comment by elv1s42** [comment]
Hi @jherbiere-giift !
Regarding `Description` attribute - I agree with you, this should be added in the next release.

Other values:
`Priority` - it is just test property, called 'Priority';
`Test type` - it is just test property, called 'TestType';
`Message` - it is the message, that NUnit sends when test is failed (for example, test is failed by assertion).

For this test:
![2017-05-17 13_49_14-ghpr nunitexamples - microsoft visual studio](https://cloud.githubusercontent.com/assets/6689884/26150624/da043cf0-3b07-11e7-851f-ccf2177a4afa.png)

You will get this report page:
![2017-05-17 13_48_50-ghp report test page](https://cloud.githubusercontent.com/assets/6689884/26150623/d9fc7ea2-3b07-11e7-8c9a-7aff2be26ff2.png)

**Comment by jherbiere-giift** [comment]
Thanks for the quick response and the extra documentation. I really appreciate it. I will be looking for the new version.

**Comment by elv1s42** [comment]
Implemented in v0.7.0
