### ISSUE TITLE
Combine 2 TestResult.xml

### ISSUE THREAD

**Issue by georgooty** [GHPReporter/Ghpr.Core#47]
Hi,

I want to know is possible to combine existing testresult.xml file with next created testresult.xml file in GHPReporter?

I have a requirement to logout the system and start the test again . But the previously executed testresults.xml is replaced by newly one. 

Please help me.

Regards,
George

**Comment by elv1s42** [comment]
Hi @georgooty !
I am not sure about what test results do you mean.

If you are talking about GHP Reports then this feature is not yet supported, it will be added in the future as part of functionality of Ghpr Console.
 
If you are talking about NUnit test results then it is possible to change test result file name when you are running tests with NUnit Console (using `--result=...` option). You can find more info here: https://github.com/nunit/docs/wiki/Console-Command-Line

**Comment by georgooty** [comment]
ok.

I meant nunit test results xml file.
