### ISSUE TITLE
Filters don't affect newly loaded tests

### ISSUE THREAD

**Issue by ParanoikCZE** [GHPReporter/Ghpr.Core#48]
When loading takes some time and you change filters during progress, unloaded tests are not affected by these changes.

To reproduce, have results loading for 2s+, refresh page and hit e.g. passed button, already loaded results are hidden, newly loaded passed records are still displayed.
Expected result is that loading should check filter status and affect visibility of results.

**Comment by elv1s42** [comment]
Hi @ParanoikCZE !

Thank you for this issue, I was able to reproduce it.
That should be pretty easy to fix.
