### ISSUE TITLE
Move charts above/below other info

### ISSUE THREAD

**Issue by ParanoikCZE** [GHPReporter/Ghpr.Core#49]
Charts now takes 2/3 of space, mostly breaking relevant info.

In test detail view, main information message often contains exception which is formatted in way that it's almost unreadable.

In main view, width of runs history chart prevents from adding more columns as more than 50 runs causes text collisions (without zooming). E.g. 
![obrazek](https://user-images.githubusercontent.com/19796452/30641538-d2c60d7a-9e07-11e7-97c7-6b1ec93eabf3.png)
So, extending this chart to 100% width should help displaying more data.

**Comment by elv1s42** [comment]
Hi @ParanoikCZE !

Thank you for this issue.
Regarding 2/3 of width: I agree, we can change it to be 100%.

If you don't want to see all test runs you can just edit .json config file (see https://github.com/GHPReporter/Ghpr.Core#about-settings-file).

Main information message also included in the Failure tab (where it has 100% width):
![image](https://user-images.githubusercontent.com/6689884/30642200-92d29d22-9e12-11e7-9871-ab9e9ec93539.png)

![image](https://user-images.githubusercontent.com/6689884/30642222-a51420dc-9e12-11e7-9808-f65af9f69544.png)

**Comment by ParanoikCZE** [comment]
More than that, we would like to see something like error progres over time in similar way as single test chart shows, so hiding is not way our here.
To failure tab, I know about that, however, if there are many failed tests, just opening them in new tab and switching them would show some issue in common, so switching to another tab is just another step.

Actually, as I'm watching this chart now, I was almost never interested in history of single test. So moving this chart to dedicated tab would be another solution.

**Comment by elv1s42** [comment]
Hi, @ParanoikCZE .
Width will be fixed in v 0.8.0 like this:
![image](https://user-images.githubusercontent.com/6689884/31240750-5a29ee2c-aa0a-11e7-927e-0a7ac2c18cfa.png)

**Comment by elv1s42** [comment]
This one is for the main report page:
![image](https://user-images.githubusercontent.com/6689884/31240959-048cd258-aa0b-11e7-8d20-5af1a82eb458.png)

**Comment by ParanoikCZE** [comment]
Great, thanks.

**Comment by elv1s42** [comment]
This was released some time ago
