### ISSUE TITLE
Test Categories Management

### ISSUE THREAD

**Issue by ParanoikCZE** [GHPReporter/Ghpr.Core#50]
Test list tree is now generated by test name split by dot. As there could be many nested levels, categories takes too much space. E.g.
It would be great to have option to switch to "collapsed version", this would look like e.g. 
![obrazek](https://user-images.githubusercontent.com/19796452/30642144-fe1af8ee-9e09-11e7-86fc-7a189c1a4797.png)

Another suggestion is to add option to disable displaying empty categories (after filtering some tests out), e.g.
![obrazek](https://user-images.githubusercontent.com/19796452/30642440-4211b122-9e0b-11e7-93a9-57cc4afd13c8.png)
Should become
![obrazek](https://user-images.githubusercontent.com/19796452/30642486-61c0a0e6-9e0b-11e7-81fd-975e5e7367fa.png)

Would be great if both options could become default for user, so storing these options to cookies would be great.

**Comment by elv1s42** [comment]
Hi!

I agree that it would be useful. but I am not sure about using cookies as this approach may not work for opening report locally without running any servers. So probably we can put all settings in json settings file: https://github.com/GHPReporter/Ghpr.Core#about-settings-file

**Comment by ParanoikCZE** [comment]
Seems like JS is able to handle this pretty easily .. 
https://www.w3schools.com/js/js_cookies.asp

**Comment by elv1s42** [comment]
Empty catigories are not displayed in current master branch. 
Collapsed list still needs to be implemented.

Target release version should be 0.9.4

**Comment by elv1s42** [comment]
Hierarchical list now doen not include empty names:
![image](https://user-images.githubusercontent.com/6689884/46654297-2c703080-cbb1-11e8-915e-e3b8db30cd34.png)

Collapsed list added too:
![image](https://user-images.githubusercontent.com/6689884/46654360-59244800-cbb1-11e8-9f46-6bb70d98e985.png)

**Comment by elv1s42** [comment]
Released as v0.9.4
