### ISSUE TITLE
[Feature] Possibility to display next/prev test in current run

### ISSUE THREAD

**Issue by ParanoikCZE** [GHPReporter/Ghpr.Core#52]
Would be great to have an option to browse through test without quitting to run view. Curently prev/next buttons navigates through runs on same test.
New buttons should follow some filters (e.g. if I filter out failed tests, I would like to browse through them to identify some root cause).

**Comment by elv1s42** [comment]
For now it will work only for next/prev test without filtering by test result.
Filtering by test result will slow down the way current page works becuase we will have to load all tests from current run to get test results:
![image](https://user-images.githubusercontent.com/6689884/46457025-80e26d00-c7b9-11e8-85d1-8ff52867337b.png)


I think we can return to this work when cache will be implemented correctly, I've created a separate issue for that: https://github.com/GHPReporter/Ghpr.Core/issues/83

@ParanoikCZE, can you please let me know if you still need this feature (I mean load next test from run with respect to test result) and I'll raise a separate issue for that.

Thank you

**Comment by ParanoikCZE** [comment]
Hi, I was thinking more about this as nice to have feature. It's nothing we can live without right now.

**Comment by elv1s42** [comment]
Released as v0.9.4
