### ISSUE TITLE
Escape test message

### ISSUE THREAD

**Issue by ParanoikCZE** [GHPReporter/Ghpr.Core#53]
Test message should be escaped before displaying, ATM, I can experience issues with <> characters. E.g. 
json source
"testMessage":"a<b"
results in displaying
Message: a

**Comment by elv1s42** [comment]
Hi @ParanoikCZE !

I did that [yesterday](https://github.com/GHPReporter/Ghpr.Core/commit/eecc3672673ac0907cf06c03dda45265554e3205), thank you for this issue.

This will be included in the next release
