### ISSUE TITLE
Dynamic properties in json file? Run from Team City

### ISSUE THREAD

**Issue by EllaVader** [GHPReporter/Ghpr.Core#55]
Is it possible to run this from TeamCity?  Would we have to put the required dlls and json files in each build agents nunit folder?  Also is it possible to put in dynamic and/or relative values in the settings.json file?  I would like the output path to be relative to where the TestResults.xml file is being generated.  Please let me know if any of this is possible on how to do this.  Thanks in advance!

**Comment by elv1s42** [comment]
Hi @EllaVader!

Thank you for this issue.
Unfortunately I didn;t teat GhpReporter with TeamCity. In general the .dll and .json files should be located in addins folder of NUnit framework.
Relative values in .json config should work.

Thank you
