### ISSUE TITLE
New to GHPReporter

### ISSUE THREAD

**Issue by PriyalakshmiNandan** [GHPReporter/Ghpr.Core#72]
Hi I have experience in Java/cucumber but right now working on Specflow/C# and I am looking out for the custom reporting add-on for the specflow project. And I am intrested in GHPReporter. I have downloaded and the GHPReporter for Specflow along with the dependencies. And I am launching the chrome with the options specified, but eventhough when I run (through Visual Studio) the specflow with GHPReporter configured [with default settings] I am not getting the report generated but my specflow is getting executed. Is there anything that I am missing?

**Comment by elv1s42** [comment]
Hi @PriyalakshmiNandan !
Can you please make sure that you have correct configuration in your tests? For some details please see: https://github.com/GHPReporter/Ghpr.SpecFlow#usage

Also please use v0.8.2 for all of the packages because the Ghpr.SpecFlow packages were not updated to a newer version.

Thank you

**Comment by PriyalakshmiNandan** [comment]
Hi Right now report is getting generated but the reports are blank. Is there any other system configuration or solution configuration that needs to done?
![ghpreporter test log](https://user-images.githubusercontent.com/42179101/43964799-84fb6dbc-9cb5-11e8-8384-b88ff0612275.JPG)
![ghpreporter run log](https://user-images.githubusercontent.com/42179101/43964804-88c4c6d2-9cb5-11e8-82e9-241cf2a15c5b.JPG)


![ghpreporter log](https://user-images.githubusercontent.com/42179101/43964775-74f7c104-9cb5-11e8-9250-8de427ed83c5.JPG)

**Comment by elv1s42** [comment]
Hi @PriyalakshmiNandan !
Good to know that your report is generated now.

To see the data loaded correctly in your browser please make sure that you are following the instructions (https://github.com/GHPReporter/Ghpr.Core#view-report-locally) on how to see the report locally.

Thank you

**Comment by PriyalakshmiNandan** [comment]
Hi Great now I am able to view the report..

**Comment by elv1s42** [comment]
Great news @PriyalakshmiNandan, thank you for the update.
Closing this issue then.
