### ISSUE TITLE
[Feature] Use code-tag or syntax highlighting JS library for stack traces in failure tab

### ISSUE THREAD

**Issue by lanzelot1989** [GHPReporter/Ghpr.Core#78]
**Is your feature request related to a problem? Please describe.**
It is not easy to read stack traces in the current format.
![image](https://user-images.githubusercontent.com/773651/45293533-ba94c080-b4f8-11e8-8095-aca234ba4f17.png)

**Describe the solution you'd like**
A "&lt;code&gt;" tag surrounding it or a special JS library like highlight.js or prismjs could solve this.
![image](https://user-images.githubusercontent.com/773651/45293667-1c552a80-b4f9-11e8-8db4-07c424f3e91b.png)

**Comment by elv1s42** [comment]
Hi @lanzelot1989 !

Agreed to use `<code>` tag for now.

Thank you for the feature request!

**Comment by elv1s42** [comment]
Tested `<code>`, looks like this:

![image](https://user-images.githubusercontent.com/6689884/45295492-942a5180-b507-11e8-903b-13a76d991f44.png)

@lanzelot1989 , if you ok with this implementation I'll include it in the v0.9.3

**Comment by lanzelot1989** [comment]
looks good to me, thank you for the quick fix - keep up the good work!

**Comment by elv1s42** [comment]
Released in v0.9.3
