### ISSUE TITLE
Nugget package

### ISSUE THREAD

**Issue by yfrindel** [GHPReporter/Ghpr.Core#9]
Hi,

I’m a software developer from France.
Your report seems to be very cool, and I would like to use it in my project.
I have an issue with the nugget package.
When I try to add the nugget package to my project I have the following message : 

Could not install package 'Ghpr.Core 0.1.4.2'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Please, could you help me ?

And do you have some documentations or tutorials about GHPReporter please ?

Thank you.

Yannick

**Comment by elv1s42** [comment]
Hi @yfrindel 

The error message is saying that there is no version of nuget packege for your framework version.
This is true, Ghpr is build for .Net 4.5.2:
![image](https://cloud.githubusercontent.com/assets/6689884/19556007/dc508afc-96c7-11e6-8513-ba6b9b7263d8.png)

Have you tried to change .Net version of your project to 4.5.2 ?

**Comment by yfrindel** [comment]
Thank you very much Evgeniy for your help.
Indeed, now, with the framework 4.5.2, all is good.
An other thing that I was forced to adapt, the fact to use the nunit console runner 3.5 instead of the the nunit console runner 3.2

kind regards

**Comment by elv1s42** [comment]
@yfrindel Thanks for the update!

Installing .Net Framework v4.5.2 and NUnit 3.5 fixed the problem, so I am closing this issue.
